---
- name: Add Cloudflare repository GPG key
  ansible.builtin.apt_key:
    url: "{{ cloudflare_repository_key_url }}"
    keyring: "{{ cloudflare_repository_key_path }}"
    state: present

- name: Add Cloudflare repository to apt sources list
  ansible.builtin.apt_repository:
    repo: "{{ cloudflare_repository }}"
    state: present

- name: Install Cloudflared
  ansible.builtin.apt:
    update_cache: true
    name: cloudflared
    state: present
