---
- name: Add Cloudflare repository to dnf repo list
  ansible.builtin.get_url:
    url: "{{ cloudflare_repository }}"
    dest: "/etc/yum.repos.d/{{ cloudflare_repository_file }}"
    mode: "0644"

- name: Install Cloudflared
  ansible.builtin.dnf:
    update_cache: true
    name: cloudflared
    state: present
